name: (Action) Build matrics app
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      runner:
        required: true
        type: string
      concurrency_group:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    strategy:
      matrix:
        rn-version: ['next', '0.72', '0.71', '0.70', '0.69', '0.68', '0.67', '0.66']
      fail-fast: false
    concurrency:
      group: ${{ inputs.concurrency_group }}-${{ matrix.rn-version }}
      cancel-in-progress: true
    steps:
      - name: Setup Java
        if: ${{ inputs.runner == 'windows-latest' }}
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create react app
        run: npx react-native@${{ matrix.rn-version }} init app --skip-install --version ${{ matrix.rn-version }}
      - name: Install Reanimated
        working-directory: app
        run: yarn add github:software-mansion/react-native-reanimated#${{ inputs.branch_name }}

      - name: Install pods
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: app/ios
        run: pod install
      - name: Build Android app
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: app
        run: npx react-native@${{ matrix.rn-version }} run-ios

      - name: Build Android app
        if: ${{ inputs.platform == 'Android' }}
        working-directory: app/android
        run: ./gradlew assembleDebug --console=plain
